### ISSUE TITLE
don't autocomplete numbers

### ISSUE THREAD

**Issue by spf2** [joefitzgerald/autocomplete-go#15]
<img width="372" alt="screen shot 2016-03-24 at 5 36 52 pm" src="https://cloud.githubusercontent.com/assets/48122/14035061/08eec8b6-f1e7-11e5-8049-1ce7fdaf5f77.png">

i guess you'd have to check the whole token to ensure it's a number? obviously if you had a variable "foo2bar" and typed "foo2", it should still autocomplete...

**Comment by joefitzgerald** [comment]
Thinking this should be addressed in `gocode` itself. Do you want to [open an issue](https://github.com/nsf/gocode/issues/new) there?

**Comment by nsf** [comment]
Gocode fails to deduce cursor context and just returns all autocompletions as a default fallback. I do trigger autocompletions in my editor manually, if your editor triggers autocompletion automatically in a place you don't want it to, that's an editor problem. Gocode returns best autocompletion suggestions it can figure out for any cursor location.

**Comment by sprt** [comment]
@joefitzgerald VS Code seems to be handling this case manually, FWIW: https://github.com/Microsoft/vscode-go/blob/eb48f2f17671612bf3ab73a2e91d06aa5ce06f52/src/goSuggest.ts#L49-L52

**Comment by crantok** [comment]
For anyone, like me, coming here to report this problem still existing, the commit that closed this issue includes this caveat:

> there seems to be a bug in the language-go grammar preventing the correct scope from being identified when a right parenthesis is to the right of a number
